const TECH_ICONS: Record<string, string> = {
  React: "gear",
  "React 18": "gear",
  TypeScript: "scroll",
  Angular: "angular",
  "Next.js": "shield",
  "Next.js 14": "shield",
  "Micro-frontends": "layers",
  "Screaming Architecture": "diamond",
  Scrum: "users",
  "Framer Motion": "sparkles",
  i18next: "globe",
  "React Native": "smartphone",
  Turborepo: "package",
  Expo: "rocket",
  "Expo Router": "router",
  Cypress: "check",
  "GitHub Actions": "workflow",
  Jest: "test",
  Zod: "zod",
  "React Hook Form": "rhf",
  "shadcn/ui": "shadcn",
  SonarQube: "sonar",
  "TanStack Query": "tanstack",
  "TanStack Table": "table",
  NextAuth: "auth",
  Recharts: "chart",
  Vitest: "vitest",
  Vite: "vite",
  "React Router": "router",
  "React Router DOM 6": "router",
  "Tailwind CSS": "tailwind",
  "Radix UI": "radix",
  Zustand: "zustand",
  Axios: "axios",
  "Testing Library": "testlib",
  Husky: "husky",
  ESLint: "eslint",
  Prettier: "prettier",
  "Material UI": "mui",
  Formik: "formik",
  Yup: "yup",
  "React Table": "table",
  "date-fns": "datefns",
  Sass: "sass",
  SCSS: "sass",
  "Styled Components": "styled",
  GSAP: "gsap",
  Lenis: "lenis",
  Spline: "spline",
  "Vue 3": "vue",
  Strapi: "strapi",
  Wagmi: "wagmi",
  Stylelint: "stylelint",
  "react-native-mmkv": "mmkv",
  "react-native-reanimated": "reanimated",
  "react-native-gesture-handler": "gesture",
  "react-native-video": "video",
  Mux: "mux",
  Sentry: "sentry",
  "React Native Testing Library": "testlib",
};

const TECH_ICON_NODES: Record<string, React.ReactNode> = {
  gear: <span className="text-xs">{"<>"}</span>,
  scroll: <span className="text-xs">TS</span>,
  angular: <span className="text-xs">NG</span>,
  shield: <span className="text-xs">N</span>,
  layers: <span className="text-xs">MF</span>,
  diamond: <span className="text-xs">SA</span>,
  users: <span className="text-xs">AG</span>,
  sparkles: <span className="text-xs">FM</span>,
  globe: <span className="text-xs">i18</span>,
  smartphone: <span className="text-xs">RN</span>,
  package: <span className="text-xs">TR</span>,
  rocket: <span className="text-xs">EX</span>,
  check: <span className="text-xs">CY</span>,
  workflow: <span className="text-xs">GH</span>,
  test: <span className="text-xs">JT</span>,
  zod: <span className="text-xs">ZD</span>,
  rhf: <span className="text-xs">RHF</span>,
  shadcn: <span className="text-xs">SH</span>,
  sonar: <span className="text-xs">SQ</span>,
  tanstack: <span className="text-xs">TQ</span>,
  table: <span className="text-xs">TT</span>,
  auth: <span className="text-xs">NA</span>,
  chart: <span className="text-xs">RC</span>,
  vitest: <span className="text-xs">VT</span>,
  vite: <span className="text-xs">VI</span>,
  router: <span className="text-xs">RR</span>,
  tailwind: <span className="text-xs">TW</span>,
  radix: <span className="text-xs">RX</span>,
  zustand: <span className="text-xs">ZU</span>,
  axios: <span className="text-xs">AX</span>,
  testlib: <span className="text-xs">TL</span>,
  husky: <span className="text-xs">HK</span>,
  eslint: <span className="text-xs">ES</span>,
  prettier: <span className="text-xs">PR</span>,
  mui: <span className="text-xs">MUI</span>,
  formik: <span className="text-xs">FK</span>,
  yup: <span className="text-xs">YP</span>,
  datefns: <span className="text-xs">DF</span>,
  sass: <span className="text-xs">SC</span>,
  styled: <span className="text-xs">SC</span>,
  gsap: <span className="text-xs">GS</span>,
  lenis: <span className="text-xs">LN</span>,
  spline: <span className="text-xs">SP</span>,
  vue: <span className="text-xs">V3</span>,
  strapi: <span className="text-xs">ST</span>,
  wagmi: <span className="text-xs">WG</span>,
  stylelint: <span className="text-xs">SL</span>,
  mmkv: <span className="text-xs">MK</span>,
  reanimated: <span className="text-xs">RA</span>,
  gesture: <span className="text-xs">GH</span>,
  video: <span className="text-xs">VD</span>,
  mux: <span className="text-xs">MX</span>,
  sentry: <span className="text-xs">SN</span>,
  code: <span className="text-xs">{"{ }"}</span>,
};

export function TechIcon({ tech }: { tech: string }) {
  const iconType = TECH_ICONS[tech] ?? "code";
  return TECH_ICON_NODES[iconType] ?? TECH_ICON_NODES.code;
}
